[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "meg_decoding_tools"
version = "0.0.1"
authors = [
  { name="Ladislas Nalborczyk", email="ladislas.nalborczyk@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}

classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://github.com/lnalborczyk/meg_decoding_tools"
Issues = "https://github.com/lnalborczyk/meg_decoding_tools/issues"