[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "meg_decoding_tools"
version = "0.0.1"
authors = [
  { name="Ladislas Nalborczyk", email="ladislas.nalborczyk@gmail.com" },
]
description = "Open source tools for MEG preprocessing, basic analyses, and multivariate pattern analyses (aka decoding), based on MNE-Python."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}

classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3"
]

dependencies = [
    "numpy>=1.21.2",
    "scipy>=1.7.1",
    "matplotlib>=3.5.0"
]

[project.urls]
Homepage = "https://github.com/lnalborczyk/meg_decoding_tools"
Issues = "https://github.com/lnalborczyk/meg_decoding_tools/issues"